export const testModel = [
  {
    accessType: 'OTHER',
    authenticationUserType: 'PERSONAL',
    capabilities: ['CREDIT_CARDS', 'IDENTITY_DATA'],
    credentialsType: 'PASSWORD',
    currency: 'SEK',
    displayName: 'American Express',
    fields: [
      {
        defaultValue: null,
        description: 'Username',
        exposed: true,
        children: null,
        helpText: null,
        hint: null,
        immutable: true,
        masked: false,
        maxLength: null,
        minLength: null,
        name: 'username',
        numeric: false,
        optional: false,
        options: null,
        pattern: null,
        patternError: null,
        type: null,
        value: null,
        sensitive: false,
        checkbox: false,
        additionalInfo: null
      },
      {
        defaultValue: null,
        description: 'Password',
        exposed: true,
        children: null,
        helpText: null,
        hint: null,
        immutable: false,
        masked: true,
        maxLength: null,
        minLength: null,
        name: 'password',
        numeric: false,
        optional: false,
        options: null,
        pattern: null,
        patternError: null,
        type: null,
        value: null,
        sensitive: true,
        checkbox: false,
        additionalInfo: null
      }
    ],
    financialInstitutionId: 'b6e0ca903b3b4f3e920ee602d3b919eb',
    financialInstitutionName: 'American Express',
    groupDisplayName: 'American Express',
    images: {
      icon: 'https://cdn.tink.se/provider-images/americanexpress.png',
      banner: null
    },
    market: 'SE',
    multiFactor: false,
    name: 'americanexpress',
    passwordHelpText:
      "Use the same username and password as you would in the card issuer's mobile app.",
    popular: false,
    status: 'TEMPORARY_DISABLED',
    transactional: true,
    type: 'CREDIT_CARD'
  },
  {
    accessType: 'OPEN_BANKING',
    authenticationUserType: 'PERSONAL',
    authenticationFlow: 'REDIRECT',
    capabilities: ['CREDIT_CARDS'],
    credentialsType: 'THIRD_PARTY_APP',
    currency: 'SEK',
    displayName: 'American Express',
    fields: [],
    financialInstitutionId: 'b6e0ca903b3b4f3e920ee602d3b919eb',
    financialInstitutionName: 'American Express',
    groupDisplayName: 'American Express',
    images: {
      icon: 'https://cdn.tink.se/provider-images/americanexpress.png',
      banner: null
    },
    market: 'SE',
    multiFactor: true,
    name: 'se-amex-ob',
    passwordHelpText:
      'You will be redirected to your card issuer to complete the authentication.',
    popular: false,
    status: 'ENABLED',
    transactional: true,
    type: 'BANK'
  },
  {
    accessType: 'OTHER',
    authenticationUserType: 'PERSONAL',
    capabilities: [
      'INVESTMENTS',
      'IDENTITY_DATA',
      'SAVINGS_ACCOUNTS',
      'LOANS',
      'MORTGAGE_AGGREGATION'
    ],
    credentialsType: 'MOBILE_BANKID',
    currency: 'SEK',
    displayName: 'Avanza',
    displayDescription: 'Mobile BankID',
    fields: [
      {
        defaultValue: null,
        description: 'Social security number',
        exposed: true,
        children: null,
        helpText: null,
        hint: 'YYYYMMDDNNNN',
        immutable: true,
        masked: false,
        maxLength: 12,
        minLength: 12,
        name: 'username',
        numeric: true,
        optional: false,
        options: null,
        pattern: '(19|20)[0-9]{10}',
        patternError: 'Please enter a valid social security number.',
        type: null,
        value: null,
        sensitive: false,
        checkbox: false,
        additionalInfo: null
      }
    ],
    financialInstitutionId: '576dad6f22594374bbada2990b4a2d31',
    financialInstitutionName: 'Avanza',
    groupDisplayName: 'Avanza',
    images: {
      icon: 'https://cdn.tink.se/provider-images/avanza.png',
      banner: null
    },
    market: 'SE',
    multiFactor: true,
    name: 'avanza-bankid',
    passwordHelpText:
      'To connect your bank, you need to identify yourself using Mobile BankID.',
    popular: true,
    status: 'ENABLED',
    transactional: true,
    type: 'BROKER'
  },
  {
    accessType: 'OTHER',
    authenticationUserType: 'PERSONAL',
    capabilities: ['LOANS'],
    credentialsType: 'PASSWORD',
    currency: 'SEK',
    displayName: 'CSN',
    fields: [
      {
        defaultValue: null,
        description: 'Social security number',
        exposed: true,
        children: null,
        helpText: null,
        hint: 'YYYYMMDDNNNN',
        immutable: true,
        masked: false,
        maxLength: 12,
        minLength: 12,
        name: 'username',
        numeric: true,
        optional: false,
        options: null,
        pattern: '(19|20)[0-9]{10}',
        patternError: 'Please enter a valid social security number.',
        type: null,
        value: null,
        sensitive: false,
        checkbox: false,
        additionalInfo: null
      },
      {
        defaultValue: null,
        description: 'PIN',
        exposed: true,
        children: null,
        helpText: null,
        hint: 'NNNN',
        immutable: false,
        masked: true,
        maxLength: 4,
        minLength: 4,
        name: 'password',
        numeric: true,
        optional: false,
        options: null,
        pattern: '([0-9]{4})',
        patternError: 'Please enter four digits.',
        type: null,
        value: null,
        sensitive: true,
        checkbox: false,
        additionalInfo: null
      }
    ],
    financialInstitutionId: 'a31f72c5214147438376027cad36745a',
    financialInstitutionName: 'CSN',
    images: {
      icon: 'https://cdn.tink.se/provider-images/csn.png',
      banner: null
    }
  }
];
